baseURL = 'https://bearcbass.github.io/'
languageCode = 'en-us'
title = "Sebastian's Portfolio"
theme = 'hugo-liftoff'

[params]

[taxonomies]
    tag = 'tags'
    category = 'categories'    
    series = 'series' # Allows you to create an organized series of posts (e.g. multi-part tutorial)
    project-type = 'project types' # Categorize projects by type (e.g. client work, personal, open source, etc.)
